version: '3.8'

services:
  mongo:
    image:  mongo:7.0.5
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 28017:27017
